apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fleet-foundation-gitops
  namespace: fleet-local
spec:
  repo: git@github.com:RobertoMachorro/fleet-foundation.git
  branch: main
  clientSecretName: gh-ssh-key
  pollingInterval: 60s
  paths:
  - infrastructure/longhorn
  - infrastructure/rancher
  - demos/website
